sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t vbrenister/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true vbrenister/docker-react npm run test

# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-2"
#   app: docker-react
#   env: "Dockerreact-env"
#   bucket_name: "elasticbeanstalk-us-east-2-859017111439"
#   bucket_path: "docker-react"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY