sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t vbrenister/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true vbrenister/docker-react npm run test